---
- name: "Apply base configuration to the server(s)"
  hosts: all
  roles:
    - base

- name: "Configure and deploy web server"
  hosts: webserver
  vars:
    domain_name: harishnarayanan.org
  roles:
    - web